export default {
  tetanus: "Tetanus",
  wounds: "Wounds",
  "blood-transfusion": "Blood Transfusion",
  nutritions: "Nutritions",
  shock: "Shock",
  mas: "Minimally Access Surgery",
  "parotid-tumor": "Parotid Tumor",
  "cervical-lymphadenopathy": "Cervical Lymphadenopathy",
  ssi: "Surgical Site Infection",
  burns: "Burns",
  neoplasia: "Neoplasia",
  "pre-op": "Pre-operative Preparations",
  "post-op": "Post-operative Complications",
  "post-op-fever": "Post-op Fever",
  haemorrhage: "Haemorrhage",
  "tb-lymphadenitis": "TB Lymphadenitis",
  tracheostomy: "Tracheostomy",
  gangrene: "Gangrene",
  ulcer: "Ulcer",
};
