export default {
  "increased-icp": "Increased ICP",
  "head-injury": "Head Injury",
  bph: "BPH",
  urolithiasis: "Urolithiasis",
  "ca-stomach": "Ca Stomach",
  "du-perforation": "DU Perforation",
  "oesophageal-varices": "Oesophageal Varices",
  "ca-rectum": "Ca Rectum",
  rif: "RIF",
  piles: "Piles",
  hernia: "Hernia",
  appendicitis: "Appendicitis",
  "breast-cancer": "Breast Cancer",
  "severe-acute-pancreatitis": "Pancreatitis",
  "obstructive-jaundice": "Obstructive Jaundice",
  choledocholithiasis: "Choledocholithiasis",
  "malignant-obstructive-jaundice": "Malignant Obstructive Jaundice",
  hcc: "Hepatocellular Carcinoma",
  "splenic-injury": "Splenic Injury",
};
