export default {
  index: "Introduction",
  cardiology: "Cardiology",
  hepatology: "Hepatology",
  haematology: "Haematology",
  "diabetes-mellitus": "Diabetes Mellitus",
  infection: "Infection",
  toxicology: "Toxicology",
  rheumatology: "Rheumatology",
  respiration: "Respiratory",
  neurology: "Neurology",
  nephrology: "Nephrology",
  endocrinology: "Endocrinology",
  aws: "Alcohol Withdrawal Syndrome",
  sjs: "Stevens Johnson Syndrome",
}
